language: python
matrix:
  include:
  # command to install dependencies
      - os: linux
        python: 3.4
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-8
              - libmpfr-dev
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-8"
      - os: linux
        python: 3.6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-8
              - libmpfr-dev
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-8"
      - os: linux
        python: 3.7
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-8
              - libmpfr-dev
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-8"
      - os: linux
        python: 3.8
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-8
              - libmpfr-dev
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-8"
      - os: linux
        python: 3.4
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-9
              - libmpfr-dev
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-9"
      - os: linux
        python: 3.6
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-9
              - libmpfr-dev
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-9"
      - os: linux
        python: 3.7
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-9
              - libmpfr-dev
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-9"
      - os: linux
        python: 3.8
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gfortran-9
              - libmpfr-dev
              - gzip
        env:
          - TRAVIS_GFORTRAN="gfortran-9"

install: 
  - pip install -r requirements.txt
  - pip install -e .[dev]
  - python setup.py install
# command to run tests
script: 
  - ./run_test.sh
env: 
  TRAVIS=1
cache: 
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
